--CREATE DATABASE [Crm]
--GO

USE [Crm]

DROP TABLE dbo.Customer
DROP TABLE dbo.Title

CREATE TABLE [dbo].[Title] (
	[Id] INT NOT NULL IDENTITY(1,1)
		CONSTRAINT PK_Title PRIMARY KEY
	,[Name] NVARCHAR(200) NOT NULL
		CONSTRAINT IQ_Title UNIQUE
	,[LongTitle] NVARCHAR(200) NULL
	,[OrderIndex] INT NOT NULL
	,[Created] DATETIMEOFFSET NOT NULL
	,[Modified] DATETIMEOFFSET NOT NULL
	,INDEX Idx_Title NONCLUSTERED ([Name], [OrderIndex])
)

CREATE TABLE [dbo].[Customer] (
	[Id] INT NOT NULL IDENTITY(1,1)
		CONSTRAINT PK_Customer PRIMARY KEY
	,[UniqueId] UNIQUEIDENTIFIER NOT NULL
	,[TitleId] INT NOT NULL
		CONSTRAINT FK_Customer_Title
		REFERENCES [dbo].[Title]([Id])
	,[Key] VARBINARY(MAX) NOT NULL
	,[FirstName] VARBINARY(MAX) NOT NULL
	,[MiddleName] VARBINARY(MAX) NULL
	,[LastName] VARBINARY(MAX) NOT NULL
	,[EmailAddress] VARBINARY(MAX) NOT NULL
	,[DateOfBirth] DATETIME NOT NULL
	,[RegistrationDate] DATETIMEOFFSET NOT NULL
	,[Created] DATETIMEOFFSET NOT NULL
	,[Modified] DATETIMEOFFSET NOT NULL
)
